[package]
name = "codezero"
version = "0.1.0"
edition = "2024"
description = "A CLI setup wizard for running CodeZero locally"
license = "MIT"
repository = "https://github.com/code0-tech/hydra"
homepage = "https://codezero.build"
readme = "README.md"
keywords = ["codezero", "cli", "setup"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.102"
clap = { version =  "4.6.1", features = ["derive"] }
console = "0.16.1"
dialoguer = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tera = "1.20.1"
ureq = { version = "2.10.1", features = ["json"] }
